#!/usr/bin/env node
/* Image pipeline (docs/15): images/ sources → public/images/ AVIF/WebP/JPEG
   at 1x/2x + inline LQIP, and a generated manifest module. Deterministic:
   same input bytes → same output. Run: pnpm build:images */
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const SRC = 'images';
const OUT = 'public/images';
const MANIFEST = 'src/lib/images.generated.ts';

/* slot → source ordinal (the "(n)" in the supplied filenames) + display width
   (CSS px at 1x) chosen from the layout slot it fills. */
const SLOTS = [
  { slot: 'waiting-room', ordinal: 1, width: 560 },
  { slot: 'arcade',       ordinal: 2, width: 480 },
  { slot: 'market',       ordinal: 3, width: 720 },
  { slot: 'kopitiam',     ordinal: 4, width: 560 },
  { slot: 'bus-stop',     ordinal: 5, width: 720 },
  { slot: 'hands',        ordinal: 6, width: 560 },
  { slot: 'corridor',     ordinal: 7, width: 480 },
  { slot: 'chair-ticket', ordinal: 8, width: 720 },
];

const files = await readdir(SRC);
const byOrdinal = new Map();
for (const f of files) {
  const m = f.match(/\((\d)\)\.png$/);
  if (m) byOrdinal.set(Number(m[1]), path.join(SRC, f));
}

await mkdir(OUT, { recursive: true });
const manifest = {};

for (const { slot, ordinal, width } of SLOTS) {
  const src = byOrdinal.get(ordinal);
  if (!src) throw new Error(`source (${ordinal}) for ${slot} missing in ${SRC}/`);
  const img = sharp(src);
  const meta = await img.metadata();
  const ratio = meta.height / meta.width;
  const widths = [width, Math.min(width * 2, meta.width)];

  for (const w of widths) {
    const resized = sharp(src).resize(w);
    await resized.clone().avif({ quality: 55 }).toFile(`${OUT}/${slot}-${w}.avif`);
    await resized.clone().webp({ quality: 74 }).toFile(`${OUT}/${slot}-${w}.webp`);
    await resized.clone().jpeg({ quality: 78, mozjpeg: true }).toFile(`${OUT}/${slot}-${w}.jpg`);
  }
  const lqip = await sharp(src).resize(24).webp({ quality: 30 }).toBuffer();

  manifest[slot] = {
    widths,
    width,
    height: Math.round(width * ratio),
    lqip: `data:image/webp;base64,${lqip.toString('base64')}`,
  };
  console.log(`✓ ${slot} ${widths.join('/')}w (${meta.width}×${meta.height})`);
}

const body =
  '/* Generated by scripts/build-images.mjs — do not edit. */\n' +
  `export const IMAGES = ${JSON.stringify(manifest, null, 2)} as const;\n`;
await writeFile(MANIFEST, body);
console.log(`wrote ${MANIFEST}`);
