/**
 * Self-host every font. A 3G Android in Brickfields must not wait on
 * fonts.google.com (docs/01 §6, G3).
 *
 * Fetches Google's woff2 CSS (unicode-range slices — browsers download only
 * the chunks a page actually uses, which is what makes self-hosted CJK
 * viable), downloads every referenced file into public/fonts/, and writes
 * src/app/fonts.css with local URLs. Run once; commit the output. Re-run only
 * to change weights or add a family.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const FAMILIES = [
  'family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400',
  'family=Vollkorn:wght@500;600;700',
  'family=Noto+Sans+Tamil:wght@400;600;700',
  'family=Noto+Serif+Tamil:wght@600;700',
  'family=Noto+Sans+SC:wght@400;600;700',
  'family=Noto+Serif+SC:wght@600;700',
];
const CSS_URL = `https://fonts.googleapis.com/css2?${FAMILIES.join('&')}&display=swap`;
// A modern-browser UA is what makes Google return woff2 + unicode-range.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36';

const outDir = 'public/fonts';
mkdirSync(outDir, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();

let n = 0;
const seen = new Map();
const rewritten = [];
// Replace every remote url() with a local file, downloading as we go.
const parts = css.split(/(url\(https:\/\/fonts\.gstatic\.com[^)]+\))/g);
for (const part of parts) {
  const m = part.match(/^url\((https:\/\/fonts\.gstatic\.com[^)]+)\)$/);
  if (!m) { rewritten.push(part); continue; }
  const remote = m[1];
  if (!seen.has(remote)) {
    const name = `f${String(n++).padStart(3, '0')}.woff2`;
    const buf = Buffer.from(await (await fetch(remote)).arrayBuffer());
    writeFileSync(join(outDir, name), buf);
    seen.set(remote, name);
  }
  rewritten.push(`url(/fonts/${seen.get(remote)})`);
}

const header = `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.\n   Self-hosted font faces; families must match the stacks in tokens.css. */\n\n`;
writeFileSync('src/app/fonts.css', header + rewritten.join(''));
console.log(`fonts: ${seen.size} files into ${outDir}, css written to src/app/fonts.css`);
